// TODO: Types
const SET_CHARACTERS = 'SET_CHARACTERS';
const TOGGLE_LOADER = 'TOGGLE_LOADER';
const SET_FAVORITE = 'SET_FAVORITE';
const DELETE_FAVORITE = 'DELETE_FAVORITE';

export { SET_CHARACTERS, TOGGLE_LOADER, SET_FAVORITE, DELETE_FAVORITE };
