// TODO: Types
const SET_CHARACTERS = 'SET_CHARACTERS';
const ADD_CHARACTERS = 'ADD_CHARACTERS';
const SET_FAVORITE = 'SET_FAVORITE';
const DELETE_FAVORITE = 'DELETE_FAVORITE';
const TOGGLE_LOADER = 'TOGGLE_LOADER';
const IT_LOADED = 'IT_LOADED';
const NUM_PAGE = 'NUM_PAGE';

export { SET_CHARACTERS, TOGGLE_LOADER, SET_FAVORITE, DELETE_FAVORITE, ADD_CHARACTERS, IT_LOADED, NUM_PAGE };
